### ISSUE TITLE
Update show-pins for 4.19 kernel

### ISSUE THREAD

**Issue by bRitch022** [mvduin/bbb-pin-utils#3]
After updating to the 4.19.59-ti-rt-r25 kernel on Beaglebone Black, the show-pins utility would not work anymore. Here are the errors:

`debian@beaglebone:/usr/local/sbin$ show-pins`
`Can't open /sys/kernel/debug/pinctrl/44e10800.pinmux/pinmux-pins: No such file or directory at /usr/local/sbin/show-pins line 54.`
`Can't open /sys/kernel/debug/pinctrl/44e10800.pinmux/pinmux-pins: No such file or directory at /usr/local/sbin/show-pins line 110.
`

I found that at both of these lines, the script needed to be appended from accessing /44e10800.pinmux/ directory to: /44e10800.pinmux-pinctrl-single/ as it is different in the updated kernel.

**Comment by mvduin** [comment]
Thank you, I'll see if I can find a more robust way to determine the path, and otherwise I'll just test for both locations.

**Comment by mvduin** [comment]
This should fix the problem, let me know if you still experience problems
