### ISSUE TITLE
no directory pinmux-pins

### ISSUE THREAD

**Issue by dmalawey** [mvduin/bbb-pin-utils#4]
Here is my output when I attempt to run the installation.   I'm not a linux pro, maybe it's an easy fix.

```
debian@beaglebone:/var/lib/cloud9$ cd /usr/local/sbin
debian@beaglebone:/usr/local/sbin$ sudo wget -N https://raw.githubusercontent.com/mvduin/bbb-pin-utils/blue/show-pins
[sudo] password for debian:
--2020-09-13 03:02:49--  https://raw.githubusercontent.com/mvduin/bbb-pin-utils/blue/show-pins
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.8.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.8.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16573 (16K) [text/plain]
Saving to: ‘show-pins’

show-pins                              100%[=========================================================================>]  16.18K  --.-KB/s    in 0.01s

Last-modified header missing -- time-stamps turned off.
2020-09-13 03:02:54 (1.17 MB/s) - ‘show-pins’ saved [16573/16573]

debian@beaglebone:/usr/local/sbin$ sudo chmod a+x show-pins
debian@beaglebone:/usr/local/sbin$ sudo show-pins | sort
Can't open /sys/kernel/debug/pinctrl/44e10800.pinmux/pinmux-pins: No such file or directory at /usr/local/sbin/show-pins line 54.
```

**Comment by mvduin** [comment]
That seems odd, what image are you running (`cat /etc/dogtag`) and what kernel version (`uname -r`) ?

**Comment by dmalawey** [comment]
BeagleBoard.org Debian Buster IoT Image 2020-04-06

Kernel: 4.19.94-ti-r51

I installed the image straight from beaglebone a day ago and then all I've done is install some packages.  They're found here:
https://github.com/MXET/SCUTTLE/blob/master/software/scripts/self_installer_part2.sh

**Comment by mvduin** [comment]
I've just tested updating the kernel on the 2020-04-06 Buster IoT image from its default (4.19.94-ti-r42) to 4.19.94-ti-r51 but as I expected this makes no difference, show-pins still works fine here.

I'm not sure what you could possibly have done to break it.. the contents of debugfs (/sys/kernel/debug) mainly depends on kernel version and to lesser extent the device tree (though no plausible dt change could result in the error you showed), and there's really nothing userspace could do to cause problems other than somehow neglecting to mount debugfs entirely.

**Comment by dmalawey** [comment]
I've already fully power cycled and rebooted.  I've also tried re-entering the directory and repeating the sudo wget command, with the same result at the end. Can you recommend any other steps for me to try this again systematically?

**Comment by mvduin** [comment]
There's nothing you can do wrong with installing show-pins, in fact you don't strictly need to install it at all, it is a self-contained script and will run from anywhere.  This must have something to do either with the dtb of the beaglebone blue (although I'm pretty sure people have used show-pins successfully on the blue) or with the installation of this SCUTTLE thing (though I don't see anything in the scripts that could explain it).

Which part of the path it complains about (`/sys/kernel/debug/pinctrl/44e10800.pinmux/pinmux-pins`) is missing exactly?  Is /sys/kernel/debug empty?  Does /sys/kernel/debug/pinctrl/44e10800.pinmux exist?

**Comment by dmalawey** [comment]
There's a file with a similar name: 

```
debian@beaglebone:/sys/kernel/debug$ cd pinctrl/
debian@beaglebone:/sys/kernel/debug/pinctrl$ ls
44e10800.pinmux-pinctrl-single  pinctrl-devices  pinctrl-maps
44e3e000.rtc                    pinctrl-handles
debian@beaglebone:/sys/kernel/debug/pinctrl$
```

**Comment by mvduin** [comment]
Apologies for the slow response. Turns out this is just issue #3, I had forgotten to apply the same fix to the beaglebone blue branch.  I've just pushed the updated branch so hopefully it should be fixed now.  Just remove show-pins (`sudo rm /usr/local/sbin/show-pins`) and install it again.  Let me know if there's any further problems.

**Comment by dmalawey** [comment]
Had some interruptions in this project - I still plan to try this next week.
