### ISSUE TITLE
Parse error on kernel 5.10

### ISSUE THREAD

**Issue by JoseGoncalves** [mvduin/bbb-pin-utils#5]
Performing some tests with Debian 11 in a BeableBone Green Wireless, I found that the `show-pins` script does not work on it.
When I try to execute it it gives me:
```
parse error at /usr/local/sbin/show-pins line 122, <> line 2.
```

**Comment by JoseGoncalves** [comment]
This seems a kernel related issue because, when running with kernel 4.19 in bullseye, it works fine.
Only when executing `show-pins` in kernel 5.10 it fails (I've tested both with 5.10.59-ti-r22 and 5.10.65-ti-r23).

**Comment by mvduin** [comment]
Yes, show-pins parses quite strictly because I'd rather have it fail than have it potentially misinterpret information, but that does mean it has to be periodically updated to deal with changes introduced by newer kernels and such.

I'll look into it
