### ISSUE TITLE
P9.15 shows up twice

### ISSUE THREAD

**Issue by Anthony-J-Garot** [mvduin/bbb-pin-utils#7]
Hi Matthijs,

Some pins show up twice. This I understand for P9.41 and P9.42 because they're special dual pins. 

But P9.15 also shows up twice.

```
root@BBBDEV:~# show-pins | sort | grep P9.15
P9.15                             16 fast rx down 7 gpio 1.16
P9.15                             34 fast rx  up  7 gpio 2.00
root@BBBDEV:~#
```

I looked at older code of yours in `/opt/scripts/device/bone/show-pins.pl`, and it appears that second line has something to do with pad T13. I looked that up on the schematic, but T13 doesn't look to be connected to a specific pin, but it does mention `gpio 2.00`, which is the same as second line of show-pins output.

Can you explain what the second line describes?

**Comment by mvduin** [comment]
> Some pins show up twice. This I understand for P9.41 and P9.42 because they're special dual pins.
> 
> But P9.15 also shows up twice.

P9.15 is in the same situation as P9.41 and P9.42, all three expansion header pins connect to two AM335x balls each.

Specifically, P9.15 connects to ball R13 (gpio 1.16) via R160 (0Ω) and to ball T13 (gpio 2.00) via R161 (0Ω).

> I looked that up on the schematic, but T13 doesn't look to be connected to a specific pin

Ehh...
![image](https://user-images.githubusercontent.com/2078931/219503848-7cebb854-af1e-45d8-8de1-2d04b5ae0e82.png)

**Comment by Anthony-J-Garot** [comment]
Well that explains it. I was looking at an old schematic. 
https://beagleboard.org/static/beaglebone/BEAGLEBONE_SCHEM_A3.pdf

🤷
